<a href="https://colab.research.google.com/github/ailunguo/Test/blob/main/Tensorflow_Test/%E5%B1%82API_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 注意力层

多头注意力层

In [ ]:
# tf.keras.layers.MultiHeadAttention(
#     num_heads,
#     key_dim,
#     value_dim=None,
#     dropout=0.0,
#     use_bias=True,
#     output_shape=None,
#     attention_axes=None,
#     kernel_initializer="glorot_uniform",
#     bias_initializer="zeros",
#     kernel_regularizer=None,
#     bias_regularizer=None,
#     activity_regularizer=None,
#     kernel_constraint=None,
#     bias_constraint=None,
#     **kwargs
# )

In [ ]:
import tensorflow as tf

In [ ]:
layer = tf.keras.layers.MultiHeadAttention(num_heads = 2, key_dim=2)
target = tf.keras.Input(shape=[8, 16])
source = tf.keras.Input(shape=[4, 16])
output_tensor, weights = layer(target, source, return_attention_scores=True)
print(output_tensor.shape)
print(weights.shape)

(None, 8, 16)
(None, 2, 8, 4)


In [ ]:
layer = tf.keras.layers.MultiHeadAttention(
    num_heads=2, key_dim=2, attention_axes=(2,3))
input_tensor = tf.keras.Input(shape=[5, 3, 4, 16])
output_tensor = layer(input_tensor, input_tensor)
print(output_tensor.shape)

(None, 5, 3, 4, 16)


注意力层

In [ ]:
tf.keras.layers.Attention(use_scale=False, score_mode="dot", **kwargs)

In [ ]:
# CNN+Attention实例
query_input = tf.keras.Input(shape=(None,), dtype='int32')
value_input = tf.keras.Input(shape=(None,), dtype='int32')

token_embedding = tf.keras.layers.Embedding(input_dim=1000, output_dim=64)
query_embeddings = token_embedding(query_input)
value_embeddings = token_embedding(value_input)

# CNNlayer
cnn_layer = tf.keras.layers.Conv1D(
    filters=100,
    kernel_size=4,
    padding='same')
query_seq_encoding = cnn_layer(query_embeddings)
value_seq_encoding = cnn_layer(value_embeddings)

query_value_attention_seq = tf.keras.layers.Attention()(
    [query_seq_encoding, value_seq_encoding])

query_encoding = tf.keras.layers.GlobalAveragePooling1D()(
    query_seq_encoding)
query_value_attention = tf.keras.layers.GlobalAveragePooling1D()(
    query_value_attention_seq)

input_layer = tf.keras.layers.Concatenate()(
    [query_encoding, query_value_attention])

附加注意力层

In [ ]:
tf.keras.layers.AdditiveAttention(use_scale=True, **kwargs)

# 重塑图层

reshape类

In [1]:
import tensorflow as tf

In [ ]:
tf.keras.layers.Reshape(target_shape, **kwargs)

In [2]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Reshape((3, 4), input_shape=(12,)))
model.output_shape

(None, 3, 4)

In [3]:
model.add(tf.keras.layers.Reshape((6, 2)))
model.output_shape

(None, 6, 2)

In [4]:
model.add(tf.keras.layers.Reshape((-1, 2, 2)))

In [5]:
model.output_shape

(None, 3, 2, 2)

Flatttn类

In [ ]:
tf.keras.layers.Flatten(data_format=None, **kwargs)

In [7]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Conv2D(64, 3, 3, input_shape=(3, 32, 32)))
model.output_shape

(None, 1, 10, 64)

In [8]:
model.add(tf.keras.layers.Flatten())
model.output_shape

(None, 640)

RepeatVector layer

In [ ]:
tf.keras.layers.RepeatVector(n, **kwargs)

In [10]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(32, input_dim = 32))
model.add(tf.keras.layers.RepeatVector(3))
model.output_shape

(None, 3, 32)

Permute layer

In [ ]:
tf.keras.layers.Permute(dims, **kwargs)

In [12]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Permute((2, 1), input_shape=(10, 64)))
model.output_shape

(None, 64, 10)

裁剪一维图形

裁剪图像时，分别在轴的首尾进行参数个的裁剪

In [ ]:
tf.keras.layers.Cropping1D(cropping=(1, 1), **kwargs)

In [13]:
import numpy as np

In [14]:
input_shape = (2, 3, 2)
x = np.arange(np.prod(input_shape)).reshape(input_shape)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [18]:
y = tf.keras.layers.Cropping1D(cropping=1)(x)
y

<tf.Tensor: shape=(2, 1, 2), dtype=int64, numpy=
array([[[2, 3]],

       [[8, 9]]])>

裁剪二维图像

In [ ]:
tf.keras.layers.Cropping2D(
    cropping=((0, 0), (0, 0)), data_format=None, **kwargs
)

In [19]:
input_shape = (2, 28, 28, 3)
x = np.arange(np.prod(input_shape)).reshape(input_shape)
y = tf.keras.layers.Cropping2D(cropping=((2, 2), (4, 4)))(x)
y.shape

TensorShape([2, 24, 20, 3])

裁剪三维图像

In [ ]:
tf.keras.layers.Cropping3D(
    cropping=((1, 1), (1, 1), (1, 1)), data_format=None, **kwargs
)

In [20]:
input_shape = (2, 28, 28, 10, 3)
x = np.arange(np.prod(input_shape)).reshape(input_shape)
y = tf.keras.layers.Cropping3D(cropping=(2, 4, 2))(x)
y.shape

TensorShape([2, 24, 20, 6, 3])

上采样一维层

In [ ]:
tf.keras.layers.UpSampling1D(size=2, **kwargs)


In [21]:
input_shape = (2, 2, 3)
x = np.arange(np.prod(input_shape)).reshape(input_shape)
x

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [24]:
y = tf.keras.layers.UpSampling1D(size=3)(x)
y

<tf.Tensor: shape=(2, 6, 3), dtype=int64, numpy=
array([[[ 0,  1,  2],
        [ 0,  1,  2],
        [ 0,  1,  2],
        [ 3,  4,  5],
        [ 3,  4,  5],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 6,  7,  8],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [ 9, 10, 11],
        [ 9, 10, 11]]])>

上采样二维

In [ ]:
tf.keras.layers.UpSampling2D(
    size=(2, 2), data_format=None, interpolation="nearest", **kwargs
)

In [25]:
input_shape = (2, 2, 1, 3)
x = np.arange(np.prod(input_shape)).reshape(input_shape)
x

array([[[[ 0,  1,  2]],

        [[ 3,  4,  5]]],


       [[[ 6,  7,  8]],

        [[ 9, 10, 11]]]])

In [31]:
y = tf.keras.layers.UpSampling2D(size=(1, 2))(x)
y

<tf.Tensor: shape=(2, 2, 2, 3), dtype=int64, numpy=
array([[[[ 0,  1,  2],
         [ 0,  1,  2]],

        [[ 3,  4,  5],
         [ 3,  4,  5]]],


       [[[ 6,  7,  8],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [ 9, 10, 11]]]])>

上采样三维图像

In [ ]:
tf.keras.layers.UpSampling3D(size=(2, 2, 2), data_format=None, **kwargs)


In [32]:
input_shape = (2, 1, 2, 1, 3)
x = tf.constant(1, shape=input_shape)
y = tf.keras.layers.UpSampling3D(size=2)(x)
y.shape

TensorShape([2, 2, 4, 2, 3])

ZeroPadding1D layer

In [ ]:
tf.keras.layers.ZeroPadding1D(padding=1, **kwargs)

In [33]:
input_shape = (2, 2, 3)
x = np.arange(np.prod(input_shape)).reshape(input_shape)
x

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [34]:
y = tf.keras.layers.ZeroPadding1D(padding=2)(x)
y

<tf.Tensor: shape=(2, 6, 3), dtype=int64, numpy=
array([[[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  1,  2],
        [ 3,  4,  5],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [ 0,  0,  0],
        [ 0,  0,  0]]])>

ZeroPadding2D layer

In [ ]:
tf.keras.layers.ZeroPadding2D(padding=(1, 1), data_format=None, **kwargs)

In [35]:
input_shape = (1, 1, 2, 2)
x = np.arange(np.prod(input_shape)).reshape(input_shape)
x

array([[[[0, 1],
         [2, 3]]]])

In [36]:
y = tf.keras.layers.ZeroPadding2D(padding=1)(x)
y

<tf.Tensor: shape=(1, 3, 4, 2), dtype=int64, numpy=
array([[[[0, 0],
         [0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 1],
         [2, 3],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0],
         [0, 0]]]])>

ZeroPadding3D layer

In [ ]:
tf.keras.layers.ZeroPadding3D(padding=(1, 1, 1), data_format=None, **kwargs)

In [38]:
input_shape = (1, 1, 2, 2, 3)
x = np.arange(np.prod(input_shape)).reshape(input_shape)
y = tf.keras.layers.ZeroPadding3D(padding=2)(x)
y.shape

TensorShape([1, 5, 6, 6, 3])

# 聚合图层

Concatenate class

In [ ]:
tf.keras.layers.Concatenate(axis=-1, **kwargs)

In [39]:
x = np.arange(20).reshape(2, 2, 5)
x

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [40]:
y = np.arange(20, 30).reshape(2, 1, 5)
y

array([[[20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29]]])

In [41]:
tf.keras.layers.Concatenate(axis=1)([x, y])

<tf.Tensor: shape=(2, 3, 5), dtype=int64, numpy=
array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [25, 26, 27, 28, 29]]])>

In [42]:
x1 = tf.keras.layers.Dense(8)(np.arange(10).reshape(5, 2)) # (5, 8)
x2 = tf.keras.layers.Dense(8)(np.arange(10, 20).reshape(5, 2)) # (5, 8)
concatted = tf.keras.layers.Concatenate()([x1, x2])
concatted.shape

TensorShape([5, 16])